### ISSUE TITLE
Получение access_token

### ISSUE THREAD

**Issue by MaratPavlov** [Phinnik/easy_vk#1]
Классно было бы сделать получение access_token и специальный эксцепшн при вызове АПИ который говорит о том, что токен протух и надо обновить.

**Comment by Phinnik** [comment]
> Классно было бы сделать получение access_token и специальный эксцепшн при вызове АПИ который говорит о том, что токен протух и надо обновить.

Получение access_token описано на этой странице: https://vk.com/dev/implicit_flow_user.
Если вы имеете в виду автоматизацию его получения, то это, к сожалению, невозможно, т.к. нет способа взять его из адресной строки браузера. Возможно лишь автоматическое собирание ссылки для авторизации и открытие ее. Это будет добавлено позже.

Эксепшены будут добавлены позже

**Comment by MaratPavlov** [comment]
Да, Вы правы. Придется использовать scope=offline для бессрочного токена.
